export const BASE_CURRENCIES = [
  'bronze',
  'silver',
  'gold',
  'diamond',
  'ruby',
  'emerald',
  'sapphire',
  'amethyst',
  'topaz',
  'opal',
  'orange',
  'pink',
  'lime',
  'cyan',
  'teal',
  'magenta',
  'indigo',
  'violet',
  'maroon',
  'brown',
  'beige',
  'coral',
  'olive',
  'navy',
  'turquoise',
  'peach',
  'mint',
  'lavender',
  'cherry',
  'apricot',
  'rose',
  'aqua',
  'limegreen',
  'mustard',
  'plum',
  'fuchsia',
  'tan',
  'salmon',
  'periwinkle',
  'charcoal',
  'crimson',
  'amber',
  'jade',
  'ivory',
  'cerulean',
  'scarlet',
  'ochre',
  'azure',
  'lilac',
  'graphite',
];

export interface WorldConfig {
  id: string;
  name: string;
  currencies: string[];
  basePrice: number;
  baseIncrement: number;
}

const WORLD_IDS = [
  'classic',
  'bars',
  'dots',
  'dots-vs-bars',
  'spinner',
  'shapes',
  'polygons',
  'progress',
  'wobbling',
  'infinity',
  'zig-zag',
  'wavy',
  'mechanic',
  'continuous',
  'growing',
  'pulsing',
  'flipping',
  'arcade',
  'hypnotic',
  'rolling',
  'glowing',
  'square',
  'bouncing',
  'filling',
  'circle',
  'square-vs-circle',
  'colorful',
  'nature',
  'time',
  'hungry',
  'shuriken',
  'dancers',
  'moving',
  'eyes',
  'line',
  'thin',
  'cut',
  'clones',
  'arrow',
  'blob',
  'maze',
  'factory',
  'three-d',
];
export const WORLDS: WorldConfig[] = WORLD_IDS.map((worldId) => ({
  id: worldId,
  name: `${worldId.charAt(0).toUpperCase() + worldId.slice(1)} World`,
  basePrice: 0.02,
  baseIncrement: 0.01,
  currencies: BASE_CURRENCIES.map((c) => c), // store only base names, prefix added later
}));
